export default {
  login: "sagartiwary",
  id: 42133389,
  node_id: "MDQ6VXNlcjQyMTMzMzg5",
  avatar_url: "https://avatars3.githubusercontent.com/u/42133389?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/sagartiwary",
  html_url: "https://github.com/sagartiwary",
  followers_url: "https://api.github.com/users/sagartiwary/followers",
  following_url:
    "https://api.github.com/users/sagartiwary/following{/other_user}",
  gists_url: "https://api.github.com/users/sagartiwary/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/sagartiwary/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/sagartiwary/subscriptions",
  organizations_url: "https://api.github.com/users/sagartiwary/orgs",
  repos_url: "https://api.github.com/users/sagartiwary/repos",
  events_url: "https://api.github.com/users/sagartiwary/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/sagartiwary/received_events",
  type: "User",
  site_admin: false,
  name: "sagartiwary",
  company: "Coding Addict",
  blog: "",
  location: "Jamshedpur",
  email: null,
  hireable: null,
  bio: "Creator of Coding Addict",
  twitter_username: "sagar tiwary",
  public_repos: 152,
  public_gists: 0,
  followers: 1495,
  following: 0,
  created_at: "2018-08-06T06:48:23Z",
  updated_at: "2020-07-08T05:01:32Z",
};
